config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser cri
        Tag kube.*
        Skip_Long_Lines On
        Buffer_Max_Size 5MB
        Mem_Buf_Limit 500MB
        Storage.Type filesystem
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Buffer_Size 2MB
        Merge_Log Off
    [FILTER]
        Name lua
        Match kube.*
        script /fluent-bit/scripts/common.lua
        call common
  outputs:
    [OUTPUT]
        Name opensearch
        Match *
        Buffer_Size 1M
        Workers 4
        Retry_Limit false
        storage.total_limit_size 500MB
        Host os.example.com
        Port 443
        tls On
        tls.verify On
        HTTP_User username
        HTTP_Passwd password
        Index <fluent-bit>
        Compress gzip
        Replace_Dots On
        Retry_Limit False
        Suppress_Type_Name On
        Trace_Error Off
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /tmp/fluent-bit
        storage.sync full
        storage.checksum off
        storage.max_chunks_up 128
        storage.backlog.mem_limit 5M
